In [ ]:
import pandas as pd

In [2]:
df = pd.read_csv('students.csv' , parse_dates=['Score Date'] )
print(df.dtypes)
df.head()

Student ID             int64
Name                     str
Age                    int64
Grade                float64
Subject                  str
City                     str
Passed                  bool
Score Date    datetime64[us]
dtype: object

   Student ID    Name  Age  Grade    Subject        City  Passed Score Date
0           1   Ahmed   25   88.0       Math       Cairo    True 2025-01-15
1           2    Sara   32   92.0    Physics  Alexandria    True 2025-02-10
2           3    Omar   19   65.0       Math        Giza   False 2025-01-20
3           4    Lina   28   78.0  Chemistry       Cairo    True 2025-03-05
4           5  Khaled   45   55.0    Physics    Mansoura   False 2025-02-28

In [3]:
print('shape of date')
print(df.shape)
print('columns')
print(df.columns)
print("data types")
print(df.dtypes)

shape of date
(9, 8)
columns
Index(['Student ID', 'Name', 'Age', 'Grade', 'Subject', 'City', 'Passed',
       'Score Date'],
      dtype='str')
data types
Student ID             int64
Name                     str
Age                    int64
Grade                float64
Subject                  str
City                     str
Passed                  bool
Score Date    datetime64[us]
dtype: object

In [4]:
print('first seven rows ')
print(df.head(7))
print("last three rows ")
print(df.tail(3))

first seven rows
   Student ID    Name  Age  Grade    Subject        City  Passed Score Date
0           1   Ahmed   25   88.0       Math       Cairo    True 2025-01-15
1           2    Sara   32   92.0    Physics  Alexandria    True 2025-02-10
2           3    Omar   19   65.0       Math        Giza   False 2025-01-20
3           4    Lina   28   78.0  Chemistry       Cairo    True 2025-03-05
4           5  Khaled   45   55.0    Physics    Mansoura   False 2025-02-28
5           6    Nour   22    NaN    English  Alexandria    True 2025-01-10
6           7    Yara   30   89.0       Math       Cairo    True        NaT
last three rows
   Student ID     Name  Age  Grade    Subject   City  Passed Score Date
6           7     Yara   30   89.0       Math  Cairo    True        NaT
7           8  Mohamed   27   72.0  Chemistry   Giza    True 2025-03-12
8           8  Mohamed   27   72.0  Chemistry   Giza    True 2025-03-12

In [ ]:
missingValues =  df.isnull().sum()
print("missing values : ")
print(missingValues)

In [6]:

avg_grade = df['Grade'].mean()
min_grade = df['Grade'].min()
max_grade = df['Grade'].max()
print(f"Average Grade: {avg_grade}")
print(f"Minimum Grade: {min_grade}")
print(f"Maximum Grade: {max_grade}")

Average Grade: 76.375
Minimum Grade: 55.0
Maximum Grade: 92.0

In [13]:
unique_city_numbers = df['City'].nunique()
unique_city_list = df['City'].unique()
print('unique_city_numbers')
print(unique_city_numbers)
print("unique_city_list")
print(unique_city_list)

unique_city_numbers
4
unique_city_list
<StringArray>
['Cairo', 'Alexandria', 'Giza', 'Mansoura']
Length: 4, dtype: str

In [11]:
df['Subject'].value_counts()

Subject
Math         3
Chemistry    3
Physics      2
English      1
Name: count, dtype: int64

In [15]:
df[['Name', 'Grade', 'Subject', 'City']]

      Name  Grade    Subject        City
0    Ahmed   88.0       Math       Cairo
1     Sara   92.0    Physics  Alexandria
2     Omar   65.0       Math        Giza
3     Lina   78.0  Chemistry       Cairo
4   Khaled   55.0    Physics    Mansoura
5     Nour    NaN    English  Alexandria
6     Yara   89.0       Math       Cairo
7  Mohamed   72.0  Chemistry        Giza
8  Mohamed   72.0  Chemistry        Giza

In [18]:
df[(df["Passed"] == True) & (df['Grade'] >= 85)]

   Student ID   Name  Age  Grade  Subject        City  Passed Score Date
0           1  Ahmed   25   88.0     Math       Cairo    True 2025-01-15
1           2   Sara   32   92.0  Physics  Alexandria    True 2025-02-10
6           7   Yara   30   89.0     Math       Cairo    True        NaT

In [19]:
df[df['Name'].str.contains('a', case=False)]

   Student ID     Name  Age  Grade    Subject        City  Passed Score Date
0           1    Ahmed   25   88.0       Math       Cairo    True 2025-01-15
1           2     Sara   32   92.0    Physics  Alexandria    True 2025-02-10
2           3     Omar   19   65.0       Math        Giza   False 2025-01-20
3           4     Lina   28   78.0  Chemistry       Cairo    True 2025-03-05
4           5   Khaled   45   55.0    Physics    Mansoura   False 2025-02-28
6           7     Yara   30   89.0       Math       Cairo    True        NaT
7           8  Mohamed   27   72.0  Chemistry        Giza    True 2025-03-12
8           8  Mohamed   27   72.0  Chemistry        Giza    True 2025-03-12

In [20]:
df[((df['City'] == 'Cairo') | (df['City'] == 'Alexandria')) & (df['Grade'] < 80)]

   Student ID  Name  Age  Grade    Subject   City  Passed Score Date
3           4  Lina   28   78.0  Chemistry  Cairo    True 2025-03-05

In [23]:

df[(df['Grade'] >= 80) & (df['Grade'] <= 90)]

   Student ID   Name  Age  Grade Subject   City  Passed Score Date
0           1  Ahmed   25   88.0    Math  Cairo    True 2025-01-15
6           7   Yara   30   89.0    Math  Cairo    True        NaT

In [24]:
df.loc[df['Name'] == 'Khaled','Grade'] =68
df[df['Name'] == 'Khaled']

   Student ID    Name  Age  Grade  Subject      City  Passed Score Date
4           5  Khaled   45   68.0  Physics  Mansoura   False 2025-02-28

In [25]:
df['Is_Excellent'] = df['Grade'] >= 90
df[['Name', "Grade","Is_Excellent"]]

      Name  Grade  Is_Excellent
0    Ahmed   88.0         False
1     Sara   92.0          True
2     Omar   65.0         False
3     Lina   78.0         False
4   Khaled   68.0         False
5     Nour    NaN         False
6     Yara   89.0         False
7  Mohamed   72.0         False
8  Mohamed   72.0         False

In [26]:
df['Grade'] = df['Grade'].fillna(df['Grade'].mean())
df[['Name', 'Grade']]

      Name  Grade
0    Ahmed   88.0
1     Sara   92.0
2     Omar   65.0
3     Lina   78.0
4   Khaled   68.0
5     Nour   78.0
6     Yara   89.0
7  Mohamed   72.0
8  Mohamed   72.0

In [27]:
common_date = df['Score Date'].mode()[0]
df['Score Date'] = df['Score Date'].fillna(common_date)
print(df.isnull().sum())

Student ID      0
Name            0
Age             0
Grade           0
Subject         0
City            0
Passed          0
Score Date      0
Is_Excellent    0
dtype: int64

In [28]:
df['Final_Grade'] = df['Grade'] + 5
df[['Name', "Grade","Final_Grade"]]

      Name  Grade  Final_Grade
0    Ahmed   88.0         93.0
1     Sara   92.0         97.0
2     Omar   65.0         70.0
3     Lina   78.0         83.0
4   Khaled   68.0         73.0
5     Nour   78.0         83.0
6     Yara   89.0         94.0
7  Mohamed   72.0         77.0
8  Mohamed   72.0         77.0

In [29]:
bins = [-1,69,79,89,100]
grades = ['Fail', 'Average', 'Good', 'Excellent']
df['Grade_Category']= pd.cut(df["Grade"], bins=bins, labels=grades)
df[['Name', "Grade","Grade_Category"]]

      Name  Grade Grade_Category
0    Ahmed   88.0           Good
1     Sara   92.0      Excellent
2     Omar   65.0           Fail
3     Lina   78.0        Average
4   Khaled   68.0           Fail
5     Nour   78.0        Average
6     Yara   89.0           Good
7  Mohamed   72.0        Average
8  Mohamed   72.0        Average

In [30]:
df.drop(columns=['Student ID'], inplace= True)
df

,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Final_Grade,Grade_Category
0,Ahmed,25,88.0,Math,Cairo,True,2025-01-15,False,93.0,Good
1,Sara,32,92.0,Physics,Alexandria,True,2025-02-10,True,97.0,Excellent
2,Omar,19,65.0,Math,Giza,False,2025-01-20,False,70.0,Fail
3,Lina,28,78.0,Chemistry,Cairo,True,2025-03-05,False,83.0,Average
4,Khaled,45,68.0,Physics,Mansoura,False,2025-02-28,False,73.0,Fail
5,Nour,22,78.0,English,Alexandria,True,2025-01-10,False,83.0,Average
6,Yara,30,89.0,Math,Cairo,True,2025-03-12,False,94.0,Good
7,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0,Average
8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0,Average

In [33]:
df = df[df['Passed'] == True]
df

,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Final_Grade,Grade_Category
0,Ahmed,25,88.0,Math,Cairo,True,2025-01-15,False,93.0,Good
1,Sara,32,92.0,Physics,Alexandria,True,2025-02-10,True,97.0,Excellent
3,Lina,28,78.0,Chemistry,Cairo,True,2025-03-05,False,83.0,Average
5,Nour,22,78.0,English,Alexandria,True,2025-01-10,False,83.0,Average
6,Yara,30,89.0,Math,Cairo,True,2025-03-12,False,94.0,Good
7,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0,Average
8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0,Average

In [34]:
df = df.sort_values(by='Grade', ascending=False)
df

,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Final_Grade,Grade_Category
1,Sara,32,92.0,Physics,Alexandria,True,2025-02-10,True,97.0,Excellent
6,Yara,30,89.0,Math,Cairo,True,2025-03-12,False,94.0,Good
0,Ahmed,25,88.0,Math,Cairo,True,2025-01-15,False,93.0,Good
3,Lina,28,78.0,Chemistry,Cairo,True,2025-03-05,False,83.0,Average
5,Nour,22,78.0,English,Alexandria,True,2025-01-10,False,83.0,Average
7,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0,Average
8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0,Average

In [35]:
df= df.sort_values(by=['City', 'Grade'], ascending=[True, False])
df

,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Final_Grade,Grade_Category
1,Sara,32,92.0,Physics,Alexandria,True,2025-02-10,True,97.0,Excellent
5,Nour,22,78.0,English,Alexandria,True,2025-01-10,False,83.0,Average
6,Yara,30,89.0,Math,Cairo,True,2025-03-12,False,94.0,Good
0,Ahmed,25,88.0,Math,Cairo,True,2025-01-15,False,93.0,Good
3,Lina,28,78.0,Chemistry,Cairo,True,2025-03-05,False,83.0,Average
7,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0,Average
8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0,Average

In [36]:
df['Rank'] = df['Grade'].rank(ascending=False, method='min')
df

,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Final_Grade,Grade_Category,Rank
1,Sara,32,92.0,Physics,Alexandria,True,2025-02-10,True,97.0,Excellent,1.0
5,Nour,22,78.0,English,Alexandria,True,2025-01-10,False,83.0,Average,4.0
6,Yara,30,89.0,Math,Cairo,True,2025-03-12,False,94.0,Good,2.0
0,Ahmed,25,88.0,Math,Cairo,True,2025-01-15,False,93.0,Good,3.0
3,Lina,28,78.0,Chemistry,Cairo,True,2025-03-05,False,83.0,Average,4.0
7,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0,Average,6.0
8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0,Average,6.0

In [37]:
df.nlargest(4, 'Grade')

,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Final_Grade,Grade_Category,Rank
1,Sara,32,92.0,Physics,Alexandria,True,2025-02-10,True,97.0,Excellent,1.0
6,Yara,30,89.0,Math,Cairo,True,2025-03-12,False,94.0,Good,2.0
0,Ahmed,25,88.0,Math,Cairo,True,2025-01-15,False,93.0,Good,3.0
5,Nour,22,78.0,English,Alexandria,True,2025-01-10,False,83.0,Average,4.0

In [38]:
df.nsmallest(3, 'Age')

,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Final_Grade,Grade_Category,Rank
5,Nour,22,78.0,English,Alexandria,True,2025-01-10,False,83.0,Average,4.0
0,Ahmed,25,88.0,Math,Cairo,True,2025-01-15,False,93.0,Good,3.0
7,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0,Average,6.0

In [40]:
high_std = df[df['Grade'] == df['Grade'].max()]
high_std[['Name','Grade']]

   Name  Grade
1  Sara   92.0

In [43]:
df.groupby('Subject')['Grade'].mean()

Subject
Chemistry    74.0
English      78.0
Math         88.5
Physics      92.0
Name: Grade, dtype: float64

In [44]:
df['avg_City'] = df.groupby('City')['Grade'].transform('mean')
df[['Name', 'City', 'Grade','avg_City']]

      Name        City  Grade  avg_City
1     Sara  Alexandria   92.0      85.0
5     Nour  Alexandria   78.0      85.0
6     Yara       Cairo   89.0      85.0
0    Ahmed       Cairo   88.0      85.0
3     Lina       Cairo   78.0      85.0
7  Mohamed        Giza   72.0      72.0
8  Mohamed        Giza   72.0      72.0

In [47]:
sub = df.groupby("Subject")['Grade'].mean()
highst_sub_name = sub.idxmax()
highst_sub_grade = sub.max()
print(highst_sub_name, " = ", highst_sub_grade)

Physics  =  92.0

In [48]:
df

,Name,Age,Grade,Subject,City,Passed,Score Date,Is_Excellent,Final_Grade,Grade_Category,Rank,avg_City
1,Sara,32,92.0,Physics,Alexandria,True,2025-02-10,True,97.0,Excellent,1.0,85.0
5,Nour,22,78.0,English,Alexandria,True,2025-01-10,False,83.0,Average,4.0,85.0
6,Yara,30,89.0,Math,Cairo,True,2025-03-12,False,94.0,Good,2.0,85.0
0,Ahmed,25,88.0,Math,Cairo,True,2025-01-15,False,93.0,Good,3.0,85.0
3,Lina,28,78.0,Chemistry,Cairo,True,2025-03-05,False,83.0,Average,4.0,85.0
7,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0,Average,6.0,72.0
8,Mohamed,27,72.0,Chemistry,Giza,True,2025-03-12,False,77.0,Average,6.0,72.0